[package]
name = "clone-gpt_back"
version = "0.1.0"
edition = "2021"

[dependencies]
hyper = "0.14.11"
hyper-tls = "0.5.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
spinner = "0.2.0"
dotenv = "0.15.0"